version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Service Aplikasi Filtering (FastAPI)
  app:
    build: .
    container_name: filtering_app_service
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  redis_data:
